export default {
  bpm: 135,
  totalBeats: 20,
  synthInit: {},
  startWaitTimeS: 0.30,
  endWaitTimeS: 2.00,
  paramSpeakersGain: 'speakers_gain',
  maxSpeakersGain: 0.5,
  startOrEndRampTimeS: 0.005,
  beatLenS: 0.2,
  startOrEndDelayS: 0.01,
  stopDelay1S: 0.1,
  stopRampDownTimeS: 0.05,
  stopDelay2S: 0.3,
}
